%% Main
% The script reads and plots the result of CUDA FAGP saved in csv format.
% For new users

close all
clear
clc

%% Set the parameters

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%% Set the following parameters to generate the datasets %%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Set the folder for the CUDA script. The matrices generated by this script
% will be saved there.
rel_input_path          = "input_matrices/";
% Set the number of dimension of the problem.
dims                    = 2;
% Set the number of considered eigenvalues.
n                       = 8;
% Set the number of training points for each dimension. The total number of
% training points will be N^dims.
N                       = 10; %15
% Set the number of test points for each dimension. The total number of
% test points will be N_test^dims.
N_test                  = 1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Generate the datasets
generateDataset(rel_input_path, dims, n, N, N_test);